"""verify_raw on a small tree: manifests written once, reused when nothing moved.

Loaded by path, like the other script tests: `scripts/` is not a package.
"""

import hashlib
import importlib.util
import json
import os
from pathlib import Path

_SPEC = importlib.util.spec_from_file_location(
    "verify_raw",
    Path(__file__).resolve().parents[1] / "scripts/round/verify_raw.py",
)
vr = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(vr)

CATALOGUED = "alt.test.mbox.zip"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def make_tree(root: Path) -> None:
    """Two data/raw entries, one loose file, a catalogued zip pool, one output dir."""
    (root / "docs").mkdir()
    raw = root / "data/raw"
    (raw / "wwwvl/sub").mkdir(parents=True)
    (raw / "wwwvl/a.txt").write_bytes(b"alpha")
    (raw / "wwwvl/sub/b.txt").write_bytes(b"beta")
    (raw / "mystery").mkdir()
    (raw / "mystery/c.txt").write_bytes(b"gamma")
    (raw / "gapfill_sample.txt").write_bytes(b"loose")
    (raw / "usenet_bulk").mkdir()
    (raw / f"usenet_bulk/{CATALOGUED}").write_bytes(b"zip bytes")
    (raw / "usenet_bulk/other.zip").write_bytes(b"not in the catalog")
    catalog = {"alt": [{"name": CATALOGUED, "size": "9", "sha1": "f" * 40}]}
    (raw / "usenet_catalog.json").write_text(json.dumps(catalog))
    (root / "output/DomainDataCollectionTask_x").mkdir(parents=True)
    (root / "output/DomainDataCollectionTask_x/delivery.txt").write_bytes(b"ship")


def rows_by_key(root: Path) -> dict[str, list[str]]:
    table = {}
    for line in (root / "docs/retention.md").read_text().splitlines():
        if line.startswith("| `"):
            cells = [c.strip().strip("`") for c in line.strip("|").split("|")]
            table[cells[0]] = cells
    return table


def mtimes(root: Path) -> dict[Path, int]:
    return {p: p.stat().st_mtime_ns for p in root.rglob("*") if p.is_file()}


def test_first_run_writes_manifests_and_table(tmp_path: Path) -> None:
    make_tree(tmp_path)
    report = vr.run(tmp_path)

    sums = (tmp_path / "data/raw/wwwvl/SHA256SUMS").read_text().splitlines()
    assert sums == sorted([f"{sha256(b'alpha')}  ./a.txt", f"{sha256(b'beta')}  ./sub/b.txt"])
    assert (tmp_path / "data/raw/wwwvl/SHA256SUMS.stat").is_file()
    assert not (tmp_path / "data/raw/wwwvl/SHA1SUMS").exists()
    # loose files share the root manifest, which never lists itself
    root_sums = (tmp_path / "data/raw/SHA256SUMS").read_text()
    assert f"{sha256(b'loose')}  ./gapfill_sample.txt" in root_sums
    assert "SHA256SUMS" not in root_sums.replace("SHA256SUMS.stat", "")

    rows = rows_by_key(tmp_path)
    assert set(rows) == {
        "data/raw/gapfill_sample.txt",
        "data/raw/mystery",
        "data/raw/usenet_bulk",
        "data/raw/usenet_catalog.json",
        "data/raw/wwwvl",
        "output/DomainDataCollectionTask_x",
    }
    wwwvl = rows["data/raw/wwwvl"]
    # priced at hostname grain on 2026-09-03 and under the bar, so kept for the record
    assert wwwvl[1:4] == ["reference", "2", "9"]
    assert wwwvl[4] == sha256("".join(f"{s}\n" for s in sums).encode())
    assert wwwvl[5] == "http://vlib.org/"
    assert wwwvl[6] == "SHA256SUMS"
    assert rows["data/raw/gapfill_sample.txt"][1] == "regenerable"
    assert rows["data/raw/gapfill_sample.txt"][6] == "line in data/raw/SHA256SUMS"
    assert rows["output/DomainDataCollectionTask_x"][1] == "regenerable"
    # an unlisted entry defaults to reference and is flagged in the report and the table
    assert rows["data/raw/mystery"][1:3] == ["reference", "1"]
    assert rows["data/raw/mystery"][5] == "unknown"
    assert any("data/raw/mystery" in f and "defaulted" in f for f in report.flags)
    assert "`data/raw/mystery`" in (tmp_path / "docs/retention.md").read_text().split("|---|")[-1]
    header = (tmp_path / "docs/retention.md").read_text().splitlines()
    assert header[0] == "# Retention"
    assert "Generated by `scripts/round/verify_raw.py`" in header[1]


def test_catalogued_zip_takes_the_ia_sha1(tmp_path: Path) -> None:
    make_tree(tmp_path)
    report = vr.run(tmp_path)
    pool = tmp_path / "data/raw/usenet_bulk"
    assert (pool / "SHA1SUMS").read_text() == f"{'f' * 40}  ./{CATALOGUED}\n"
    assert (pool / "SHA256SUMS").read_text() == f"{sha256(b'not in the catalog')}  ./other.zip\n"
    # alpha, beta, gamma, loose, catalog, other.zip, delivery: the catalogued zip is not hashed
    assert report.hashed == 7
    row = rows_by_key(tmp_path)["data/raw/usenet_bulk"]
    assert row[2:4] == ["2", str(9 + len(b"not in the catalog"))]
    assert row[6] == "SHA256SUMS, SHA1SUMS"
    expect = f"{sha256(b'not in the catalog')}  ./other.zip\n{'f' * 40}  ./{CATALOGUED}\n"
    assert row[4] == sha256(expect.encode())


def test_second_run_writes_nothing(tmp_path: Path) -> None:
    make_tree(tmp_path)
    vr.run(tmp_path)
    before = mtimes(tmp_path)
    report = vr.run(tmp_path)
    assert report.hashed == 0
    assert report.written == []
    assert mtimes(tmp_path) == before


def test_only_the_changed_file_is_rehashed(tmp_path: Path) -> None:
    make_tree(tmp_path)
    vr.run(tmp_path)
    changed = tmp_path / "data/raw/wwwvl/a.txt"
    changed.write_bytes(b"ALPHA")
    os.utime(changed, ns=(1, 1))
    (tmp_path / "data/raw/wwwvl/sub/b.txt").unlink()
    report = vr.run(tmp_path)
    assert report.hashed == 1
    sums = (tmp_path / "data/raw/wwwvl/SHA256SUMS").read_text()
    assert sums == f"{sha256(b'ALPHA')}  ./a.txt\n"
    assert any("wwwvl: 1 files in the last SHA256SUMS are gone" in f for f in report.flags)
    assert rows_by_key(tmp_path)["data/raw/wwwvl"][2:4] == ["1", "5"]


def test_dry_run_touches_nothing(tmp_path: Path) -> None:
    make_tree(tmp_path)
    before = mtimes(tmp_path)
    report = vr.run(tmp_path, dry_run=True)
    assert report.hashed == 7
    assert tmp_path / "data/raw/wwwvl/SHA256SUMS" in report.written
    assert tmp_path / "docs/retention.md" in report.written
    assert mtimes(tmp_path) == before
    assert not (tmp_path / "docs/retention.md").exists()


def test_entry_scans_one_and_keeps_the_other_rows(tmp_path: Path) -> None:
    make_tree(tmp_path)
    vr.run(tmp_path)
    (tmp_path / "data/raw/mystery/c.txt").write_bytes(b"GAMMA!")
    (tmp_path / "data/raw/wwwvl/a.txt").write_bytes(b"changed but not selected")
    report = vr.run(tmp_path, only="mystery")
    assert report.hashed == 1
    rows = rows_by_key(tmp_path)
    assert len(rows) == 6
    assert rows["data/raw/mystery"][3] == "6"
    # the unselected entry's row still reads from its manifests of the last run
    assert rows["data/raw/wwwvl"][3] == "9"
    # a loose file selected alone leaves the other loose lines in the shared manifest
    vr.run(tmp_path, only="data/raw/gapfill_sample.txt")
    root_sums = (tmp_path / "data/raw/SHA256SUMS").read_text()
    assert "./usenet_catalog.json" in root_sums and "./gapfill_sample.txt" in root_sums


def test_legacy_manifest_without_sidecar_is_rehashed(tmp_path: Path) -> None:
    """wwwvl's older SHA256SUMS lists itself and has no .stat, so its lines are not trusted."""
    make_tree(tmp_path)
    legacy = tmp_path / "data/raw/wwwvl/SHA256SUMS"
    legacy.write_text(f"{'0' * 64}  ./a.txt\n{'e' * 64}  ./SHA256SUMS\n")
    # before its first scan, the row reads off the legacy file as it stands
    rows = vr.run(tmp_path, only="mystery").rows
    wwwvl = next(r for r in rows if r.key == "data/raw/wwwvl")
    assert (wwwvl.files, wwwvl.record) == (None, "SHA256SUMS")
    report = vr.run(tmp_path)
    assert (
        report.hashed == 6
    )  # mystery was hashed by the run above; the legacy lines are not reused
    assert legacy.read_text() == "".join(
        f"{s}\n"
        for s in sorted([f"{sha256(b'alpha')}  ./a.txt", f"{sha256(b'beta')}  ./sub/b.txt"])
    )


def test_a_frozen_directory_shares_its_roots_manifest(tmp_path: Path) -> None:
    """`submissions/phase-N` is frozen, so its lines go to `submissions/SHA256SUMS`."""
    make_tree(tmp_path)
    phase = tmp_path / "submissions/phase-4"
    phase.mkdir(parents=True)
    (phase / "ark.tar.gz").write_bytes(b"tarball")
    (phase / "report.md").write_bytes(b"report")
    (tmp_path / "submissions/README.md").write_bytes(b"not an entry")
    (tmp_path / "data/archive").mkdir()
    (tmp_path / "data/archive/merged260727.tar.zst").write_bytes(b"release")

    vr.run(tmp_path)
    assert sorted(p.name for p in phase.iterdir()) == ["ark.tar.gz", "report.md"]
    shared = (tmp_path / "submissions/SHA256SUMS").read_text().splitlines()
    assert shared == sorted(
        [f"{sha256(b'tarball')}  ./phase-4/ark.tar.gz", f"{sha256(b'report')}  ./phase-4/report.md"]
    )
    rows = rows_by_key(tmp_path)
    assert "submissions/README.md" not in rows
    phase_row = rows["submissions/phase-4"]
    assert phase_row[1:4] == ["reference", "2", "13"]
    assert phase_row[4] == sha256("".join(f"{s}\n" for s in shared).encode())
    assert phase_row[5:7] == ["none", "lines in submissions/SHA256SUMS"]
    release = rows["data/archive/merged260727.tar.zst"]
    assert release[1] == "reference"
    assert release[5:7] == ["reviewer_release", "line in data/archive/SHA256SUMS"]

    # unchanged, so nothing is rewritten; a file gone from the frozen tree is flagged
    assert vr.run(tmp_path).written == []
    (phase / "report.md").unlink()
    report = vr.run(tmp_path)
    assert any(
        "submissions/phase-4: 1 files in the last SHA256SUMS are gone" in f for f in report.flags
    )
    assert rows_by_key(tmp_path)["submissions/phase-4"][2] == "1"


def test_within_names_a_line_relative_to_its_entry(tmp_path: Path) -> None:
    own = tmp_path / "own"
    own.mkdir()
    assert vr.within(own, own, "./a/b.txt") == "a/b.txt"
    loose = tmp_path / "root/x.bak"
    assert vr.within(loose, tmp_path / "root", "./x.bak") == "x.bak"
    assert vr.within(loose, tmp_path / "root", "./y.bak") is None
    shared = tmp_path / "root/phase-4"
    assert vr.within(shared, tmp_path / "root", "./phase-4/report.md") == "report.md"
    assert vr.within(shared, tmp_path / "root", "./phase-40/report.md") is None


def test_entry_that_does_not_exist_exits(tmp_path: Path) -> None:
    make_tree(tmp_path)
    try:
        vr.run(tmp_path, only="nothing_here")
    except SystemExit as exc:
        assert "nothing_here" in str(exc)
    else:
        raise AssertionError("expected SystemExit")


def test_cli(tmp_path: Path, capsys) -> None:
    make_tree(tmp_path)
    assert vr.main(["--root", str(tmp_path), "--dry-run"]) == 0
    out = capsys.readouterr()
    assert "would hash 7 files" in out.out
    assert "flag: data/raw/mystery" in out.err
    assert vr.main(["--root", str(tmp_path)]) == 0
    assert (tmp_path / "docs/retention.md").is_file()


def test_every_class_name_is_one_of_six() -> None:
    keys = [
        f"data/raw/{n}"
        for t in (
            vr.KEEP_UNTIL_PRICED,
            vr.KEEP_UNTIL_DECIDED,
            vr.KEEP_UNTIL_DECIDED_ITEMS,
            vr.LIVE_INPUT,
            vr.REFERENCE,
            vr.REGENERABLE,
        )
        for n in t
    ]
    keys += [f"data/raw/{n}" for n in vr.KEEP_JOURNAL]
    keys += ["output/x", "feedback/x", "data/ark.duckdb.x.bak"]
    classes = {vr.classify(k)[0] for k in keys}
    assert classes == {
        "live_input",
        "keep_journal",
        "keep_until_priced",
        "keep_until_decided",
        "reference",
        "regenerable",
    }
    # the E9.5 batch priced 24 of the audit's 26; these two wait on terms, not on value
    assert set(vr.KEEP_UNTIL_PRICED) == {"antispam_media", "internic_zones"}
    # priced and not spent: the bytes a yes would be ingested from
    assert set(vr.KEEP_UNTIL_DECIDED) == {"ukwa", "usenet_bulk", "usenet_new"}
    # a priced pool keeps its item journals and gives the archives back
    # every hierarchy read whole overnight on 2026-09-04 keeps its item journals
    assert len(vr.KEEP_UNTIL_DECIDED_ITEMS) == 11
    assert all(
        k.startswith("usenet_") and k.endswith("_items") for k in vr.KEEP_UNTIL_DECIDED_ITEMS
    )
    assert not set(vr.KEEP_UNTIL_DECIDED) & set(vr.REFERENCE)
    assert vr.classify("data/raw/never_heard_of") is None
    assert vr.classify("data/ark.duckdb") is None
