"""Write the one-line decision sheet: every measured source still waiting on a human word.

Ivo, 2026-08-24: *"be very concise in naming what the evidence standard of a source is, so I can
quickly decide yes/no from 1 to 2 lines of information."*

**Why a program.** `approved-sources-list.md` holds two different populations under one heading:
sixty-odd triage entries nobody has measured yet, and a handful that are measured and only need a
word. Reading the file top to bottom does not separate them, so the measured ones wait behind the
speculative ones. This pulls out exactly the second population.

**A source appears here only if it carries a `- measured:` line.** That is deliberate: a number in
prose can be a projection, a gross figure or a guess, and this sheet is what a decision gets made
from. `- measured:` means net-new post-split equivalent-English against the store, and writing one
is a claim that it was counted.

    uv run python scripts/decision_sheet.py            # rewrite docs/decisions-open.md
    uv run python scripts/decision_sheet.py --check     # exit 1 if stale, write nothing
"""

import argparse
import re
import sys
from pathlib import Path

DOC = Path("docs/approved-sources-list.md")
OUT = Path("docs/decisions-open.md")

MASTER_ELIGIBLE = {
    "prior_reused",
    "cdx_timestamp",
    "artifact_listing",
    "link_source",
    "dated_directory",
    "whois_creation",
}

HEADER = """# Open decisions

Generated by `scripts/decision_sheet.py` from `approved-sources-list.md`. Do not edit by hand.

Every row is measured: the figure is net-new post-split equivalent-English against the store, not
gross and not a projection. Answer each with one word, in `approved-sources-list.md`:

- **master** means it may date a year in the annual files.
- **candidate-only** means collect it, never let it date a year.
- **rejected** binds, and the request generator refuses to reopen it.

A `link_target` or `typed` class needs no decision at all: it can never date a year, so it is
collected without asking. Only the master-eligible classes below are blocked on you.

"""


def parse(text: str) -> tuple[list[dict], list[str]]:
    """(rows, unmeasured). Pending entries with a figure, and the ones without.

    **The second list is returned rather than dropped, because dropping it silently
    is how a 7,216.9 EE source stayed off this sheet for six days.** The 2026-08-23
    compaction of `approved-sources-list.md` cut reasoning to one line per entry and
    took some `- measured:` lines with it, so `ia_webdataservices_cctld_extraction`
    became invisible here while `docs/sources.md` still carried its measurement. A
    sheet that shows what it can and says nothing about what it cannot reads as
    complete, and a reviewer working from it will believe the queue is empty when it
    is not.
    """
    rows = []
    unmeasured: list[str] = []
    for block in re.split(r"\n### ", text)[1:]:
        head, _, body = block.partition("\n")
        if not re.search(r"^Decision: pending", body, re.M):
            continue
        measured = re.search(r"^- measured:\s*([\d,.]+)\s*(.*)$", body, re.M)
        if not measured:
            source, _, etype = head.strip().partition(" / ")
            if etype.strip() in MASTER_ELIGIBLE:
                unmeasured.append(f"{source.strip()} / {etype.strip()}")
            continue
        source, _, etype = head.strip().partition(" / ")
        # The field wraps over indented continuation lines in the source file, and a
        # single-line match silently truncates the standard mid-sentence.
        standard = re.search(r"^- what dates one item:\s*(.+?)(?=\n- |\n\n|\Z)", body, re.M | re.S)
        rows.append(
            {
                "source": source.strip(),
                "etype": etype.strip(),
                "ee": float(measured.group(1).replace(",", "")),
                "note": measured.group(2).strip().rstrip(","),
                # A `|` inside the standard silently breaks the markdown table and eats
                # the EE column: the `antispam_media_blocklist` row rendered its evidence
                # figure as "JavaScript Object Notation" because the field quoted a
                # pipe-delimited listing row verbatim. Escape rather than strip, so a
                # verbatim quote stays verbatim.
                "standard": (
                    " ".join(standard.group(1).split()).replace("|", "\\|")
                    if standard
                    else "NOT STATED"
                ),
            }
        )
    rows.sort(key=lambda r: -r["ee"])
    unmeasured.sort()
    return rows, unmeasured


def _footer(unmeasured: list[str]) -> str:
    if not unmeasured:
        return ""
    listed = "`, `".join(unmeasured[:12])
    more = f", and {len(unmeasured) - 12} more" if len(unmeasured) > 12 else ""
    return (
        f"\n{len(unmeasured)} further master-eligible classes are pending with "
        f"**no measured figure**, so they are not rows above and this sheet is not the "
        f"whole queue. Price one before deciding it, or read its verdict in "
        f"`docs/sources.md`: `{listed}`{more}.\n"
    )


def render(rows: list[dict], unmeasured: list[str] | None = None) -> str:
    unmeasured = unmeasured or []
    if not rows:
        return (
            HEADER
            + "Nothing measured is waiting. Every measured source has a decision.\n"
            + _footer(unmeasured)
        )
    lines = [
        HEADER,
        "| Source | Evidence type | What dates one item | Net-new EE |",
        "|---|---|---|--:|",
    ]
    total = 0.0
    for r in rows:
        blocked = r["etype"] in MASTER_ELIGIBLE
        if blocked:
            total += r["ee"]
        lines.append(
            f"| `{r['source']}` | `{r['etype']}`{'' if blocked else ' (not blocking)'} "
            f"| {r['standard']} | {r['ee']:,.0f} |"
        )
    lines.append("")
    lines.append(f"**{len(rows)} rows, {total:,.0f} equivalent-English waiting on a word.**")
    lines.append(_footer(unmeasured))
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the sheet is stale")
    args = ap.parse_args()

    rows, unmeasured = parse(DOC.read_text())
    want = render(rows, unmeasured)
    if args.check:
        have = OUT.read_text() if OUT.exists() else ""
        if have != want:
            print(f"{OUT} is stale; run scripts/decision_sheet.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(want)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
