"""Transcribe Prof. Ding's own task files into `docs/ding/`, verbatim.

The body is pandoc's conversion of his `.docx`, never retyped, because a paraphrase
of the brief is the one document in this repository that must not exist. Only a
provenance header is added, carrying the sha256 of the source file so a later
reader can prove the transcription belongs to that exact document.

Rerun after any new task package arrives:

    uv run python scripts/extract_ding_docs.py --package feedback-phase-N
"""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

HEADER = """<!-- Generated by scripts/extract_ding_docs.py. Do not hand-edit: rerun it. -->

# {title}

**This is a direct instruction from Professor Xiaowei Ding. It is his document, not
ours, and it outranks everything in this repository except a later message from him.**

| | |
|---|---|
| source file | `{src}` |
| sha256 | `{sha}` |
| delivered in | {archive} |
| transcribed | {stamp} by `scripts/extract_ding_docs.py` |

Verbatim below. Nothing is summarised, reordered or corrected. To check the
transcription, run `pandoc -f docx -t gfm --wrap=none` over the source file and
diff against everything under the rule.

---

"""

# source file, output name, title. Filenames carry his own dates, so a package
# that renames one is a signal to look rather than something to guess around.
DOCS = (
    (
        "Internet_Digital_Ark_Project_0815_Update.docx",
        "project-brief.md",
        "The task brief (Internet Digital Ark Project, 2026-08-15 update)",
    ),
    ("Update_Log.docx", "update-log.md", "The task brief update log"),
    ("Task_Package_File_Guide.txt", "task-package-file-guide.md", "Task package file guide"),
)


def body(src: Path) -> str:
    if src.suffix == ".docx":
        text = subprocess.run(
            ["pandoc", "-f", "docx", "-t", "gfm", "--wrap=none", str(src)],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    else:
        text = "```\n" + src.read_text(encoding="utf-8").rstrip() + "\n```\n"
    # pandoc escapes backticks it finds in the docx body; the brief uses them for
    # filenames, so the escape is noise rather than meaning.
    text = text.replace("\\`", "`")
    text = text.replace("’", "'").replace("‘", "'")
    text = text.replace("“", '"').replace("”", '"')
    # The brief is written with hyphens. Assert rather than rewrite: silently
    # changing his punctuation is what "verbatim" forbids, and a dash appearing
    # here means the source changed and wants reading. Spelled as escapes because
    # the house rule bans the literal characters from every file including this one.
    assert not re.search("[\u2013\u2014]", text), f"{src.name} carries a dash we do not allow"
    return text.strip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--package", type=Path, default=REPO / "feedback-phase-6")
    ap.add_argument("--out", type=Path, default=REPO / "docs" / "ding")
    ap.add_argument(
        "--archive", default="https://www.transfernow.net/dl/20260817w4qMbvxo (2026-08-17)"
    )
    ap.add_argument("--stamp", default="2026-08-18")
    args = ap.parse_args()

    package = args.package.resolve()
    rel = package.relative_to(REPO) if package.is_relative_to(REPO) else package
    args.out.mkdir(parents=True, exist_ok=True)
    for name, out_name, title in DOCS:
        src = package / name
        sha = hashlib.sha256(src.read_bytes()).hexdigest()
        text = HEADER.format(
            title=title,
            src=f"{rel}/{name}",
            sha=sha,
            archive=f"`{rel}/`, from {args.archive}",
            stamp=args.stamp,
        ) + body(src)
        (args.out / out_name).write_text(text, encoding="utf-8")
        print(f"{args.out / out_name}: {len(text.splitlines())} lines, sha {sha[:16]}")


if __name__ == "__main__":
    main()
