"""Normalise the four capture-dated ccTLD register listings, and split only the curated ones.

**The split is decided per artifact, not per source, because these four are two different
things.** CLAUDE.md's rule is that anything a HUMAN TYPED needs another source to date the
domain first. A registry printing its own register is not that: the registry is the body that
grants the name, so its listing is the authoritative record that the name exists. That is why
`cctld_register_listing_inbody` (TWNIC, IDNIC, RESTENA) is ingested with no split step at all.
A third party's hand-kept directory of other people's domains is the opposite, and takes the
split like any other curated list.

So, one line of reasoning each:

- **SaudiNIC `AllSA`**, no split. The page calls itself "A searchable directory for all
  registered domains under .SA" and is generated by `indexing.cgi` straight out of the
  register. The registry is stating its own register's contents.
- **`.nu` `notRenewed.cfm`**, no split. NU Domain's own expiry list, generated by its CFM
  script, and every row carries a machine-written `Expired` date of its own.
- **ISOC-IL `domains.html`**, SPLIT APPLIED. Not a register dump: a hand-kept directory of
  Israeli domains with an organisation description typed beside each one
  (`arachim.ac.il - Michlalah - Jerusalem`). A person typed these.
- **NIC Malta `um.edu.mt/nic/dir/`**, SPLIT APPLIED, and it is kept only for the record. The
  page says of itself "This directory is not updated regularly" and "Sites are not required
  to be on-line prior to name registration. This means that some of the links below may still
  be unreachable", so it refuses the liveness claim the class rests on. It measures 1.8 EE.

**The year comes from the artifact in every case**: the `.nu` rows carry their own expiry
date, ISOC-IL self-stamps `Document Modified: 3-1-98`, and the other two are fixed by their
Wayback capture, which is what `cdx_timestamp` means.

    uv run python scripts/split_cctld_capture.py            # report only
    uv run python scripts/split_cctld_capture.py --write
"""

import argparse
import re
import sys
from decimal import Decimal
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ark.canonical import to_registrable  # noqa: E402
from ark.db import DEFAULT_DB_PATH, connect_read_only_patiently  # noqa: E402
from ark.english_share import weight_of  # noqa: E402

SRC = Path("data/raw/cctld_capture")
# `<a href=...>0372-pizza.nu</a> ... 09-Nov-2001`: the name and its own expiry date.
_NU_ROW = re.compile(
    r"<a href=[^>]*>([a-z0-9][a-z0-9.\-]*\.nu)</a>.*?(\d{2})-([A-Za-z]{3})-(\d{4})",
    re.I | re.S,
)

# (file, slug, stamp, tld, year, split). `split=True` means only already-held names
# earn a year; see the module docstring for why it differs per artifact.
ARTIFACTS = [
    ("saudinic-allsa-20010414.html", "saudinic", "20010414", "sa", 2001, False),
    ("isocil-domains-19980120.html", "isocil", "19980120", "il", 1998, True),
    ("ummt-nicdir-19980525.html", "nicmalta", "19980525", "mt", 1998, True),
]


def names_of(path: Path, tld: str) -> set[str]:
    """Registrable domains under one TLD, read from the tag-stripped page."""
    flat = re.sub(r"<[^>]*>", " ", path.read_text(encoding="utf-8", errors="replace"))
    found = re.finditer(rf"\b([a-z0-9][a-z0-9.\-]*\.{tld})\b", flat, re.I)
    return {d for m in found if (d := to_registrable(m.group(1).lower()))}


def nu_rows(path: Path) -> dict[int, set[str]]:
    """`.nu` names grouped by the expiry year printed in their own row."""
    raw = path.read_text(encoding="utf-8", errors="replace")
    out: dict[int, set[str]] = {}
    for name, _day, _mon, year in _NU_ROW.findall(raw):
        if (domain := to_registrable(name.lower())) is not None:
            out.setdefault(int(year), set()).add(domain)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="write the lanes")
    args = ap.parse_args()

    editions: list[tuple[str, str, int, set[str], bool]] = []
    for filename, slug, stamp, tld, year, split in ARTIFACTS:
        path = SRC / filename
        if not path.is_file():
            print(f"  missing {path}, skipping")
            continue
        editions.append((slug, stamp, year, names_of(path, tld), split))
    nu_path = SRC / "nu-notrenewed-20011222.html"
    if nu_path.is_file():
        for year, names in sorted(nu_rows(nu_path).items()):
            # One row expires in 2003. Out of window, so it cannot date a year.
            if not 1996 <= year <= 2001:
                print(f"  .nu {year}: {len(names)} name(s) out of window, dropped")
                continue
            editions.append((f"nu{year}", "20011222", year, names, False))
    if not editions:
        print(f"nothing under {SRC}; run collect_cctld_capture.py first")
        return 1

    conn = connect_read_only_patiently(DEFAULT_DB_PATH)
    try:
        corroborated = {
            row[0] for row in conn.execute("SELECT DISTINCT domain FROM domain_year").fetchall()
        }
    finally:
        conn.close()
    print(f"{len(corroborated):,} domains already carry an assigned year\n")

    dated_ee = Decimal(0)
    for slug, stamp, year, names, split in editions:
        keep = sorted(n for n in names if n in corroborated) if split else sorted(names)
        park = sorted(n for n in names if n not in corroborated) if split else []
        dated_ee += sum((Decimal(weight_of(n.rsplit(".", 1)[-1])) for n in keep), Decimal(0))
        note = "split applied" if split else "registry dump, no split"
        print(
            f"  {slug} {stamp} ({year}): {len(names):,} names -> "
            f"{len(keep):,} dated, {len(park):,} candidate  [{note}]"
        )
        if args.write:
            (SRC / f"cctldcap-dated.{slug}.{year}.txt").write_text("\n".join(keep) + "\n")
            if park:
                (SRC / f"cctldcap-cand.{slug}.{year}.txt").write_text("\n".join(park) + "\n")

    print(f"\ngross EE of the dated lanes (before removing pairs already held): {dated_ee:,.1f}")
    if not args.write:
        print("\nreport only. Pass --write to emit the lanes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
